### ISSUE TITLE
Should money be able to accept Int32?

### ISSUE THREAD

**Issue by wout** [crystal-money/money#6]
I am building an app with Lucky and where I have a model `Product` with a column `price_cents : Int32?` and method `#price : Money`:

```cr
def price : Money
  Money.new(price_cents, "EUR")
end
```

But this code will throw the following error:

```
20 | Money.new(price_cents, "EUR")
            ^--
Error: no overload matches 'Money.new' with types (Int32 | Nil), String

Overloads are:
 - Money.new(amount : BigDecimal | BigRational, currency, bank)
 - Money.new(amount : Float, currency, bank)
 - Money.new(fractional : Int, currency, bank)
 - Money.new(pull : JSON::PullParser)
 - Money.new(amount : Number = 0, currency = Money.default_currency)
Couldn't find overloads for these types:
 - Money.new(Nil, String)
```

Is there a specific reason why `Int32` is not accepted as a value? Converting `to_i` does the trick, but in my scenario `price_cents` can be `Nil`, so I am ending up with:

```cr
def price : Money
  Money.new((price_cents || 0).to_i, "EUR")
end
```

Which works, but it is not as nice.

**Comment by Sija** [comment]
It does. you're just passing `Int32?`.

**Comment by wout** [comment]
I am wrong indeed, the error is the following:

```
Couldn't find overloads for these types:
 - Money.new(Nil, String)
```

Because `price_cents` is `Int32?` and not `Int32`. So `Int32` is accepted, but obviously `Nil` is not.

**Comment by wout** [comment]
Still wrapping my head around strong types. Takes some getting used to after years of Ruby. :smile: I'll close this issue.
